### ISSUE TITLE
Change of warmup behavior in BenchmarkTools

### ISSUE THREAD

**Issue by gdalle** [awadell1/PkgJogger.jl#70]
I think this will affect your (awesome) package once I merge it

https://github.com/JuliaCI/BenchmarkTools.jl/pull/330

**Comment by awadell1** [comment]
Thank you! It'll break a few tests (I test for no warnings during warmup, which now has a depreciation warning), but everything works functionally.

**Comment by gdalle** [comment]
merged it!
